# stage one
FROM node:lts-alpine as builder

# install dependencies for node-gyp
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.20/main/ \
    python3 make g++ || (sleep 5 && apk add --no-cache python3 make g++)

WORKDIR /app

COPY ./package.json .
RUN npm install

# stage two
FROM node:lts-alpine

ENV NODE_ENV=development

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY . .
COPY --from=builder /app/node_modules /home/node/app/node_modules

CMD [ "./node_modules/.bin/nodemon", "--config", "nodemon.json", "bin/www" ]